from dotenv import load_dotenv
import os

from parser import file2dict
from llm_request import send_prompt


def create_prompt(source, analysis, draft):
    return f"""\
You are tasked with proofreading a translation that has been revised for improved fluency. The refined
translation has been generated by editing the draft translation.

**Proofreading and Final Editing**
The goal is to provide a polished final translation of the source text. For you reference, below are the
source text, the analysis, and refined translations.
Keep the line structure similar to the Source Text.

Source Text
{source}

Analysis Translation
{analysis}

Refined Translation
{draft}

Please proofread the refined text for grammar, spelling, punctuation, terminology, and overall fluency.
Ensure the translation accurately reflects the original meaning and style.
Edit the refined translation acordingly, try to match translation of a native speaker.
Provide only the final, polished translation.
"""


if __name__ == '__main__':
    load_dotenv()
    llm_token = os.getenv('LLM_TOKEN')

    # Read file
    source_file = file2dict('data/descent_source.xml')
    analysis_file = file2dict('data/descent_analysis.xml')
    draft_file = file2dict('data/descent_direct.xml')

    tries = 5
    correct = 0

    for source, analysis, draft in zip(source_file, analysis_file, draft_file):
        for i in range(tries):
            prompt = create_prompt(
                ''.join(source['content']),
                ''.join(analysis['content']),
                ''.join(draft['content'])
            )

            result = send_prompt(prompt, llm_token)
            if result['status'] == 200:
                print(result['content'])
                print(i, 'SUCCESS', result['duration'])
                correct += 1
            else:
                print(result['content'])
                print(i, 'ERROR?')
    print(f'\nCorrect {correct}/{tries}.')
